sync exercise docs
exercism/powershell pull request #333
Opened 2024-01-14 22:42 UTC by glaxxie

2024-01-14 22:57 UTC, IsaacG requested changes
The docs changes all look fine. The meta test changes all look suspect.

2024-01-14 22:57 UTC, IsaacG commented on exercises/practice/anagram/.meta/tests.toml
> +[630abb71-a94e-4715-8395-179ec1df9f91]
Is this supposed to be matched with a test change?

2024-01-14 22:57 UTC, IsaacG commented on exercises/practice/custom-set/.meta/tests.toml
> +description = "Sets with the same elements are equal -> set is equal to a set constructed from an array with duplicates"
Should this be matched with a test change?

2024-01-14 22:57 UTC, IsaacG commented on exercises/practice/dnd-character/.meta/tests.toml
> +[dca2b2ec-f729-4551-84b9-078876bb4808]
Should this be matched with a test change?

2024-01-14 22:57 UTC, IsaacG commented on exercises/practice/grains/.meta/tests.toml
> +description = "returns the total number of grains on the board"
Ditto

2024-01-14 22:57 UTC, IsaacG commented on exercises/practice/isbn-verifier/.meta/tests.toml
> +description = "valid isbn"
Ditto

2024-01-14 23:36 UTC, IsaacG approved these changes

2024-01-15 07:33 UTC, ErikSchierboom approved these changes

2024-01-15 17:33 UTC, merged